### ISSUE TITLE
error while importing easygems.healpix 

### ISSUE THREAD

**Issue by dspraturi** [mpimet/easygems#10]
I was trying to import easygems.healpix on my computer and it is giving me an error saying `ImportError: cannot import name 'trapz' from 'scipy.integrate'`. My kernel is using python 3.12.4 and I could see that scipy version 1.14.0 is present in it.

**Comment by d70-t** [comment]
Apparently [scipy 1.14.0 removed the (deprecated) `trapz` function](https://github.com/scipy/scipy/releases/tag/v1.14.0) in favor of the new name `trapezoid`. This function is used by `healpy` and thus by `easygems`. [Healpy fixed this problem](https://github.com/healpy/healpy/pull/953) last week, but there is not yet a new release of healpy available.

For now, the best workaround likely is to downgrade `scipy` to `<1.14.0` until there's a new release of `healpy`. We may or may not draft a new release of `easygems` requiring this.
Once the fix in `healpy` is merged, we should add a dependency to the newest version of `healpy`.

**Comment by dspraturi** [comment]
Thank you! :) Switching to version 1.13.1 worked.

**Comment by lkluft** [comment]
Should we require `scipy<1.14.0` and release a new minor release for now?

**Comment by lkluft** [comment]
> Should we require `scipy<1.14.0` and release a new minor release for now?

Or we are fast with #11 and circumvent the issue ;)

**Comment by d70-t** [comment]
> Should we require `scipy<1.14.0` and release a new minor release for now?

Yes, I'd vote for this. Probably `healpy` will still take a few moments to make a new release and #11 at the moment seems to to be a little more involved than initially expected.

**Comment by d70-t** [comment]
Ok, there's now easygems 0.0.8 which includes the temporary scipy restriction.

**Comment by lkluft** [comment]
Do we consider the temporary fix as sufficient to close this issue? Or do we keep it as reminder to undo the fix when a new healpy is released?
