### ISSUE TITLE
Reconsider which healpix backend to use

### ISSUE THREAD

**Issue by d70-t** [mpimet/easygems#11]
Currently we are using the [healpy](https://github.com/healpy/healpy) library for healpix related calculations. This library is based on the original [HEALPix](https://healpix.sourceforge.io) package, which seems to sometimes create headaches for the healpy developers, and there's a motion to [gradually move away from it](https://github.com/healpy/healpy/issues/717). Furthermore, healpy pulls in a lot of unnecessary dependencies by default (e.g. matplotlib and scipy). Healpy [wants to move away from this](https://github.com/healpy/healpy/pull/910) but this move seems to be slowed down due to issues with the HEALPix C++ library as well. These issues give rise to the idea of reconsidering if we should even stick with healpy itself (the project seems to want to go in the right direction) or if we should directly use one of the alternatives (because it removes a layer of indirection, and we likely won't use most of the additional features healpy brings in).

Potential alternatives could be:

* [x] [healpix](https://github.com/ntessore/healpix) based on a small C implementation, requires only numpy, BSD licensed
* [ ] [ducc](https://github.com/mreineck/ducc) several algorithms, including healpix, (re-) written in C++, aims to be similar to the original HEALPix API, GPL licensed
* [ ] [astropy-healpix](https://astropy-healpix.readthedocs.io/en/latest/) another small re-implementation of healpix, BSD licensed

**Comment by lkluft** [comment]
I agree that a lighter dependency would be desirable. From a quick look at the alternatives that have been proposed, I would prefer `healpix`. The API seems to be straightforward and close to `healpy`. The only risk is the rather small user base at the moment. But I would argue that switching again in the future is still a rather small penalty.

**Comment by d70-t** [comment]
Yes, I agree. `healpix` would also be my first choice from a quick review. And as long as we don't re-expose APIs from those libraries, we shouldn't have a huge problem changing the backend again.

**Comment by d70-t** [comment]
It's actually not as straight forward as initially expected: We currently use the [`healpy.get_interp_val`](https://healpy.readthedocs.io/en/latest/generated/healpy.pixelfunc.get_interp_val.html) function, which computes bilinear interpolation weights. There's apparently not drop-in replacement in `healpix`.
