### ISSUE TITLE
Distribution license of easygems?

### ISSUE THREAD

**Issue by mahf708** [mpimet/easygems#14]
If you don't mind, I'd like to add easygems to conda-forge: https://github.com/conda-forge/staged-recipes/pull/27019.

1. Would you please mind adding a license file or clarifying the license terms surrounding this package? Otherwise, it is not possible to distribute the package if it not clear what the licensing terms are.
1. Would one of the maintainers be interested in being involved? This is not needed

**Comment by lkluft** [comment]
Thanks for opening the PR! 👍  I would also support the MIT license, as it is slightly less annoying for potential reuse. But I don't have a strong opinion, so if @d70-t is fine with BSD-3, we can stick with it ☺️

**Comment by lkluft** [comment]
We added the MIT license to this project
